os: linux
dist: xenial
language: node_js
cache: npm
jobs:
  include:
    - stage: test
      language: node_js
      os: osx
      script: npm run test:integration
    - stage: test
      language: node_js
      os: linux
      dist: xenial
      services:
        - xvfb
      addons:
        chrome: stable
        firefox: latest
      script:
      - npm run test:unit
    - stage: test
      addons:
        chrome: stable
      before_script:
      - npm install -g @lhci/cli@0.6.x
      script:
      - npm run build:prpl-server
      - lhci autorun
    - stage: test
      os: linux
      addons:
        sonarcloud:
          organization: "iceicerickert-github"
      script: sonar-scanner
    - stage: deploy
      node_js: '10'
      branches:
        only:
          - master
      before_script:
        - npm install -g firebase-tools
        - npm run install:functions:ci
      script:
        - npm run build:firebase
      after_success:
        - npm run deploy:firebase -- --token $FIREBASE_TOKEN
