language: node_js
# matrix:
#   include:
#   - node_js: '10'
#     os: osx
#     script: npm run test:integration
#   - node_js: '10'
#     sudo: required
#     os: linux
#     dist: trusty
#     addons:
#       chrome: stable
#       firefox: latest
#     before_script:
#     - export DISPLAY=:99.0
#     - sh -e /etc/init.d/xvfb start
#     script:
#     - npm run test:unit
jobs:
  include:
    - stage: test
      node_js: '10'
      os: osx
      script: npm run test:integration
    - stage: test
      sudo: required
      os: linux
      dist: trusty
      addons:
        chrome: stable
        firefox: latest
      before_script:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      script:
      - npm run test:unit
    - stage: deploy
      node_js: '10'
      branches:
        only:
          - master
      before_script:
        - npm install -g firebase-tools
      script:
        - npm run build:firebase
      after_success:
        - firebase deploy --only functions,hosting --token $FIREBASE_TOKEN
